version: "2"
services:
  easypush:
    build: .
    restart: unless-stopped
    networks:
      - webserver
    expose:
      - "80"
    volumes:
      - ~/easypush-volume:/app/store/data

networks:
  webserver:
      external: true
