version: "3.2"
services:
  easypush:
    build: .
    networks:
      - webserver
    ports:
      - "80"
    volumes:
      - ~/easypush-volume:/app/store/data

networks:
  webserver:
      external: true
